# Generated by Django 2.1.4 on 2018-12-21 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='salam', max_length=20),
            preserve_default=False,
        ),
    ]
