# Generated by Django 2.1.4 on 2019-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190103_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='token',
            new_name='activation_token',
        ),
        migrations.AddField(
            model_name='account',
            name='forget_password_token',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
