# Generated by Django 2.1.4 on 2019-01-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190103_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
