# Generated by Django 2.1.4 on 2019-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
