# Generated by Django 2.1.4 on 2019-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20190203_0616'),
        ('account', '0012_auto_20190203_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
