dist: bionic
sudo: false

language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - python manage.py collectstatic --noinput
  - python manage.py migrate
script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: "5db58067-89b9-447c-96b1-f5a3c1f34008"
  app: hidden-temple-28665
