# Generated by Django 2.1.4 on 2018-12-21 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateField(default=datetime.date(2018, 12, 21)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(default='گوشت', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
