# Generated by Django 2.1.4 on 2019-01-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productkind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ProductKind'),
        ),
    ]
