# Generated by Django 2.1.4 on 2019-01-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190103_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productkind',
            old_name='kind',
            new_name='name',
        ),
    ]
