# Generated by Django 2.1.4 on 2019-01-03 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190103_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 3, 9, 4, 32, 991635, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
