# Generated by Django 2.1.4 on 2019-01-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Cancelled'), ('D', 'Done')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
