# Generated by Django 2.1.4 on 2019-01-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_address'),
        ('purchase', '0002_auto_20190123_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Address'),
        ),
    ]
