# Generated by Django 2.1.4 on 2019-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
