# Generated by Django 2.1.4 on 2019-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20190124_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
