# Generated by Django 2.1.4 on 2019-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20190124_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
