# Generated by Django 2.1.4 on 2019-02-01 10:33

from django.db import migrations, models
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20190124_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reference_token',
            field=models.CharField(default=purchase.models.generate_random_token, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('I', 'In Review'), ('C', 'Cancelled'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
