# Generated by Django 2.1.4 on 2019-02-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20190203_0616'),
        ('purchase', '0008_auto_20190201_1107'),
    ]

    operations = [
    ]
