# Generated by Django 2.0.10 on 2019-02-03 18:53

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20190203_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
