# Generated by Django 2.0.10 on 2019-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20190203_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='locationX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='locationY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
